version: '3.5'

services:

  #nome do servico
  angular-crud:

    #construido a partir de uma imagem customizada em ./image
    image: angular-crud
    
    #nome do conteiner
    container_name: angular-crud

    #pastas compartilhadas
    volumes:
      #pasta do codigo fonte da aplicacao
      - "./app:/usr/src/app"

    #porta a ser exposta
    ports:
      - 4200:4200
      - 3001:3001
  
    #artifício para manter o container aberto
    tty: true
